accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import AccountList, account_detail, account_cru


urlpatterns = [
    url(r'l/$', AccountList.as_view(), name='account_list'),
    url(r'p/(?P<uuid>[\w-]+)/$', account_detail, name='account_detail'),
    url(r'new/$', account_cru, name='account_new'),
    url(r'edit/(?P<uuid>[\w-]+)/$', account_cru, name='account_update'),
]

cheapcrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from marketing.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'login/$',auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'login/$', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    # url(r'logout/$', auth_views.logout, {'next_page':'/'}),
    url(r'logout/$', auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    url(r'^subscribe/', include('subscribers.urls',namespace='subscribers')),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^contact/', include('contacts.urls',namespace='contact')),
    url(r'^comm/', include('communications.urls',namespace='comm')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^$', HomePage.as_view(), name='home')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import contact_detail, contact_cru, ContactDelete 


urlpatterns = [
    # url(r'l/$', AccountList.as_view(), name='contact_list'),
    url(r'c/new/$', contact_cru, name='contact_new'),
    url(r'c/(?P<uuid>[\w-]+)/$', contact_detail, name='contact_detail'),
    url(r'c/edit/(?P<uuid>[\w-]+)/$', contact_cru, name='contact_update'),
    url(r'c/delete/(?P<pk>[\w-]+)/$', ContactDelete.as_view(), name='contact_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

from shortuuidfield import ShortUUIDField

from django.urls import reverse




class Account(models.Model):
    uuid = ShortUUIDField(unique=True)
    name = models.CharField(max_length=80)
    desc = models.TextField(blank=True)
    address_one = models.CharField(max_length=100)
    address_two = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50)
    province = models.CharField(max_length=2)
    phone = models.CharField(max_length=20)
    owner = models.ForeignKey(User)
    created_on = models.DateField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'accounts'


    def __str__(self):
        return u"%s" % self.name


    def get_absolute_url(self):
        return reverse('accounts:account_detail', args=[self.uuid])


    def get_update_url(self):
        return reverse('accounts:account_update', args=[self.uuid])

    def get_delete_url(self):
        return reverse('accounts:account_delete', args=[self.uuid])

accounts/forms.py
from django import forms

from .models import Account


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name', 'desc', 'address_one', 'address_two', 'city', 'province', 'phone')
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder':'Company',
                    'class':'col-md-12 form-control'
                }
            ),
            'desc': forms.Textarea(
                attrs={
                    'placeholder':'Enter a description',
                    'class':'form-control'
                }
            ),
            'address_one': forms.TextInput(
                attrs={
                    'placeholder':'Street Address',
                    'class':'gi-form-addr form-control'
                }
            ),
            'address_two': forms.TextInput(
                attrs={
                    'placeholder':'Suite, PO, etc',
                    'class':'gi-form-addr form-control'
                }
            ),
            'city': forms.TextInput(
                attrs={
                    'placeholder':'City',
                    'class':'gi-form-addr form-control'
                }
            ),
            'province': forms.TextInput(
                attrs={
                    'placeholder':'Province',
                    'class':'gi-form-addr form-control'
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'placeholder':'Phone',
                    'class':'gi-form-addr form-control'
                }
            ),
        }

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseForbidden,Http404,HttpResponseRedirect 
from django.shortcuts import get_object_or_404

from django.core.urlresolvers import reverse
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .forms import AccountForm
from .models import Account

from contacts.models import Contact
from communications.models import Communication
from communications.forms import CommunicationForm


class AccountList(ListView):
    model = Account
    paginate_by = 12
    template_name = 'accounts/account_list.html'
    context_object_name = 'accounts'

    def get_queryset(self):
        try:
            a = self.request.GET.get('account',)
        except KeyError:
            a = None
        if a:
            account_list = Account.objects.filter(
                name__icontains=a, 
                owner=self.request.user
        )
        else:
            account_list = Account.objects.filter(owner=self.request.user)
        return account_list

    @method_decorator(login_required)
    def dispatch(self,*args,**kwargs):
        return super(AccountList, self).dispatch(*args, **kwargs)


@login_required()
def account_detail(request, uuid):

    account = Account.objects.get(uuid=uuid)
    if account.owner != request.user:
        return HttpResponseForbidden()

    contacts = Contact.objects.filter(account=account)
    communications = Communication.objects.filter(account=account).order_by('-created_on')
    
    form = CommunicationForm()

    context ={
        'account': account,
        'contacts': contacts,
        'communications': communications,
        'form': form
    }
    template = 'accounts/account_detail.html'
    return render(request, template, context)

@login_required()
def account_cru(request, uuid=None):

    if uuid:
        account = get_object_or_404(Account, uuid=uuid)
        if account.owner != request.user:
            return HttpResponseForbidden()
    else:
        account = Account(owner=request.user)


    # if request.method == 'POST':
    if request.POST:
        form = AccountForm(request.POST, instance=account)
        if form.is_valid():
            # account = form.save(commit=False)
            # account.owner = request.user
            account.save()
            redirect_url = reverse(
                'accounts:account_detail', args=(account.uuid,)
            )
            return HttpResponseRedirect(redirect_url)
    else:
        form = AccountForm(instance=account)

    context = {
        'form': form,
        'account': account
    }

    if request.is_ajax():
        template = 'accounts/account_item_form.html'
    else:
        template = 'accounts/account_cru.html'

    return render(request, template, context)

templates/accounts/account_cru.html
{% extends 'base.html' %}
{% block title %}Account Creation | {{ block.super }}{% endblock %}

{% block content %}
<div id="content-container" class="container p-none" style="padding-top: 100px;">
    <div class="side-p">
        {% include 'accounts/account_item_form.html' %}
    </div>
</div>
{% endblock %}

templates/accounts/account_detail.html
{% extends 'base.html' %}
{% block title %}{{ account.name }}|{{ block.super }}{% endblock %}

{% block content %}
<div id="content-container" class="container p-none">
    <div id="ad-container">
        <div id="gi-container" class="ad-container" style="padding-top:100px;">
            {% include 'accounts/account_item_view.html' %}
        </div>
    </div>
    {# List Contacts #}
    <div id="cd-container" class="ad-container">
        <div class="ad-headers">
            <h4 class="ad-mh m-none">Contacts</h4>
        </div>
        <div id="cd-body" class="row">
            <table id="cd-table" class="table table-hover">
                <tbody>
                    <tr></tr>
                    {% for contact in contacts %}
                        {% include 'contacts/contact_item_view.html' %}
                    {% endfor %}
                </tbody>
            </table>
            {# New Contact Link #}
            <a href="{% url 'contact:contact_new' %}?account={{ account.id }}" id="new-contact" class="btn btn-link">New Contact</a>
        </div>
    </div>
    {# List Communications #}
    <div id="co-container" class="ad-container" style="padding-top: 50px;">
        <div class="ad-headers">
            <h4 class="ad-mh m-none">Communications</h4>
        </div>
        <div id="co-body" class="ad-container">
            {# List of COmmunications #}
            <ul id="co-list" class="strip-list col-md-12 p-none">
                {% for comm in communications %}
                    {% include 'communications/comm_item_view.html' %}
                {% endfor %}
            </ul>
            {# Communications Item Form #}
            <div id="co-form-wrapper">
                {% include 'communications/comm_item_form.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/account_item_form.html
<form id="gi-form" action="{% if account.uuid %}{{ account.get_update_url }}{% else %}{% url 'accounts:account_new' %}{% endif %}" method="POST">
    {% csrf_token %}
    <div id="gi-h-w">
        <h3 class="gi-mh">{{ form.name }}</h3>
        <span>{{ form.name.errors }}</span>
    </div>
    <div class="row">
        <div class="col-md-9">
            <p>{{ form.desc }}</p>
            <span>{{ form.desc.errors }}</span>
        </div>
        <div class="col-md-3">
            <p class="nm">{{ form.address_one }}</p>
            <span>{{ form.address_one.errors }}</span>
            <p class="nm">{{ form.address_two }}</p>
            <span>{{ form.address_two.errors }}</span>
            <p class="nm">{{ form.city }}</p>
            <span>{{ form.city.errors }}</span>
            <p class="nm">{{ form.province }}</p>
            <span>{{ form.province.errors }}</span>
            <p class="nm">{{ form.phone }}</p>
            <span>{{ form.phone.errors }}</span>
        </div>
    </div>
    <input type="submit" id="gi-form-submit" class="btn-shadow btn-shadow-primary" value="Save">
    <p>{{ form.non_field_error }}</p>
</form>

templates/accounts/account_item_view.html
<div class="gi-header">
    <h3 class="ad-mh">{{ account.name }}
        {# Account Edit Link #}
        <span>
            <a href="{{ account.get_update_url }}" class="ad-control edit-account btn btn-link">Edit</a>
        </span>
    </h3>
</div>

<div class="row gi-body">
    <div class="col-md-9">
        <h5 class="h5-responsive gi-sh">Description</h5>
        <p>{{ account.desc }}</p>
    </div>
    <div class="col-md-3">
        <h5 class="gi-sh h5-responsive">Address</h5>
        <p class="nm">{{ account.address_one }}</p>
        <p class="nm">{{ account.address_two }}</p>
        <p class="nm">{{ account.city }}, {{ account.province }}</p>
        <p class="nm">{{ account.phone }}</p>
    </div>
</div>

templates/accounts/account_list.html
{% extends 'base.html' %}
{% block title %}Account List|{{ block.super }}{% endblock %}


{% block content %}
<div id="content-container" class="container p-none" style="padding-top:100px;">
    <div id="al-container" class="side-p">
        <div id="al-control">
            <h4>Welcome {{ user }}</h4>
                <div class="search-field clearfix">
                    <form action="{% url 'accounts:account_list' %}" method="GET" class="input-search float-right" autocomplete="on">
                        <i class="ion-android-search"></i>
                        <input type="text" name="account" value="{{ request.GET.account }}" class="input-search" placeholder="Search...">
                        <!-- <button type="submit">Search</button> -->
                        <!-- <input type="submit" value="Search" class="btn-shadow btn-shadow-success btn-shadow-md"> -->
                    </form>
                </div>
            <hr>
            <h3 class="ad-mh">Accounts Owned
                <span class="float-right">
                    <a href="{% url 'accounts:account_new' %}" class="btn-shadow btn-shadow-warning p-r-none">+ Add New Account</a>
                </span>

            </h3>
        </div>
        {# List of Accounts #}
        <br>
        <div id="al-group" class="strip-list">
            {% for account in accounts %}
                <div class="al-item clearfix">
                    <a href="{{ account.get_absolute_url }}" style="" class="float-left"><h4 class="al-name">{{ account.name }}</h4></a><span class="al-created float-right">created on {{ account.created_on }}</span>
                </div>
                <hr>
            {% endfor %}
            </div>
        {% if is_paginated %}
            <div id="al-paginate">
                <ul class="strip-list al-pgnt-list">
                    {% if page_obj.has_previous %}
                    <li class="pull-left">
                        <a href="{% url 'accounts:account_list' %}?page={{ page_obj.previous_page_number }}{% if request.GET.account %}&account={{ request.GET.account }}{% endif %}">Prev</a>
                    </li>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <li class="pull-right">
                        <a href="{% url 'accounts:account_list' %}?page={{ page_obj.next_page_number }}{% if request.GET.account %}&account={{ request.GET.account }}{% endif %}">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}