accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import AccountList, account_detail, account_cru


urlpatterns = [
    url(r'l/$', AccountList.as_view(), name='account_list'),
    url(r'p/(?P<uuid>[\w-]+)/$', account_detail, name='account_detail'),
    url(r'new/$', account_cru, name='account_new'),
    url(r'edit/(?P<uuid>[\w-]+)/$', account_cru, name='account_update'),
]

cheapcrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from marketing.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'login/$',auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'login/$', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    # url(r'logout/$', auth_views.logout, {'next_page':'/'}),
    url(r'logout/$', auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    url(r'^subscribe/', include('subscribers.urls',namespace='subscribers')),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^contact/', include('contacts.urls',namespace='contact')),
    url(r'^comm/', include('communications.urls',namespace='comm')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^$', HomePage.as_view(), name='home')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communications/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import comm_cru, comm_detail, CommDelete 


urlpatterns = [
    url(r'new/$', comm_cru, name='comm_new'),
    url(r'd/(?P<uuid>[\w-]+)/$', comm_detail, name='comm_detail'),
    url(r'edit/(?P<uuid>[\w-]+)/$', comm_cru, name='comm_update'),
    url(r'delete/(?P<pk>[\w-]+)/$', CommDelete.as_view(), name='comm_delete'),
]

communications/models.py
from django.db import models
from django.contrib.auth.models import User

from accounts.models import Account
from shortuuidfield import ShortUUIDField

from django.urls import reverse


TYPE_LIST = (
        (1, 'Meeting'),
        (2, 'Phone'),
        (3, 'Email'),
    )

class Communication(models.Model):
    uuid = ShortUUIDField(unique=True)
    subject = models.CharField(max_length=50)
    notes = models.TextField()
    kind = models.PositiveSmallIntegerField(choices=TYPE_LIST)
    date = models.DateField()
    owner = models.ForeignKey(User)
    account = models.ForeignKey(Account)
    created_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'communications'


    def __str__(self):
        return u"%s" % self.subject
    
    def get_absolute_url(self):
        return reverse('comm:comm_detail', args=[self.uuid])


    def get_update_url(self):
        return reverse('comm:comm_update', args=[self.uuid])


    def get_delete_url(self):
        return reverse('comm:comm_delete', args=[self.id])

communications/forms.py
from django import forms

from .models import Communication


class CommunicationForm(forms.ModelForm):
    class Meta:
        model = Communication
        fields = ('subject','notes','kind','date','account')
        widgets = {
            'subject': forms.TextInput(
                attrs={
                    'placeholder':'Subject',
                    'class':'form-control'
                }
            ),
            'notes': forms.Textarea(
                attrs={
                    'placeholder':'Add notes...',
                    'class':'form-control'
                }
            ),
            'kind': forms.Select(
                attrs={
                    'placeholder':'Type',
                    'class':'form-control'
                }
            ),
            'date': forms.DateInput(
                attrs={
                    'placeholder':'Date',
                    'class':'form-control'
                }
            ),
        }

communications/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import HttpResponseForbidden
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView
from django.http import Http404


from .models import Communication
from .forms import CommunicationForm
from accounts.models import Account




@login_required()
def comm_cru(request, uuid=None, account=None):

    if uuid:
        comm = get_object_or_404(Communication, uuid=uuid)
        if comm.owner != request.user:
            return HttpResponseForbidden()
    else:
        comm = Communication(owner=request.user)
    
    if request.method == 'POST':
        form = CommunicationForm(request.POST, instance=comm)
        if form.is_valid():
            #make sure the user owns the account
            account = form.cleaned_data['account']
            if account.owner != request.user:
                return HttpResponseForbidden()

            # save the data
            # comm = form.save(commit=False)
            # comm.owner = request.user
            # comm.save()
            form.save()

            # return the user to the account detail view
            if request.is_ajax():
                return render(request, 'communications/comm_item_view.html',{'comm':comm, 'account':account}
            )
            else:
                reverse_url = reverse('accounts:account_detail', args=(account.uuid,))
                return HttpResponseRedirect(reverse_url)
        else:
            # if the form isn't valid, still fetch the account so it can be passed to the template 
            account = form.cleaned_data['account']
    else:
        form = CommunicationForm(instance=comm)

    # this is used to fetch the account if it exists as a URL parameter
    if request.GET.get('account', ''):
        account = Account.objects.get(id=request.GET.get('account', ''))

    context = {
        'form': form,
        'comm': comm,
        'account': account
    }
    
    if request.is_ajax():
        template = 'communications/comm_item_form.html'
    else:
        template = 'communications/comm_cru.html'

    return render(request, template, context)


@login_required()
def comm_detail(request, uuid):
    
    comm = Communication.objects.get(uuid=uuid)
    if comm.owner != request.user:
        return HttpResponseForbidden()
    template = 'communications/comm_detail.html'
    context = {'comm':comm}
    return render(request, template, context)


class CommMixin(object):
    model = Communication

    def get_context_data(self, **kwargs):
        kwargs.update({'object_name':'Communication'})
        return kwargs

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CommMixin, self).dispatch(*args,**kwargs)


class CommDelete(CommMixin, DeleteView):
    template_name = 'object_confirm_delete.html'

    def get_object(self, queryset=None):
        obj = super(CommDelete, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        account = Account.objects.get(id=obj.account.id)
        self.account = account
        return obj

    def get_success_url(self):
        return reverse(
            'accounts:account_detail', args=(self.account.uuid,)
    )

templates/communications/comm_cru.html
{% extends 'base.html' %}
{% block title %}Communication | {{ block.super }}{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none" style="padding-top: 100px;">
        <h4 class="ad-mh">Add a Communication</h4>
        {% include 'communications/comm_item_form.html' %}
    </div>
{% endblock %}

templates/communications/comm_detail.html
{% extends 'base.html' %}
{% block title %}Communications | {{ block.super }}{% endblock %}


{% block content %}
<div id="content-container" class="container p-none" style="padding-top: 100px;">
    <ul id="co-list" class="strip-list col-md-12 p-none"> 
        {% include 'communications/comm_item_view.html' %}
    </ul>
</div>
{% endblock %}

templates/communications/comm_item_form.html
<form id="comm-form" action="{% if comm.uuid %}{% url 'comm:comm_update' %}{% else %}{% url 'comm:comm_new' %}{% endif %}" method="POST">
    {% csrf_token %}
    <p>{{ form.subject }}</p>
    <div id="comm-form-internals">
        <p>{{ form.subject.errors }}</p>
        <p>{{ form.notes }}</p>
        <p>{{ form.notes.errors }}</p>
        <table class="table comm-form">
            <tbody>
                <tr>
                    <td>{{ form.kind }}</td>
                    <td>{{ form.date }}</td>
                    <td class="comm-submit-td">
                        <input type="submit" class="btn-shadow btn-shadow-success btn-shadow-sm comm-submit" value="Save">
                    </td>
                </tr>
                <tr>
                    <td>{{ form.kind.errors }}</td>
                    <td>{{ form.date.errors }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
    <input type="hidden" id="id_account" name="account" value="{% if request.GET.account %}{{ request.GET.account }}{% else %}{{ account.id }}{% endif %}">
    <input type="hidden" id="id_owner" name="owner" value={{ user.username }}>
</form>

templates/communications/comm_item_view.html
<li class="co-item list-unstyled" style="padding-top: 10px;">
    <h6 class="co-item-h">{{ comm.subject }} 
        <span>
            {# Comm Edit URL #}
            <a href="{{ comm.get_update_url }}?account={{ account.id }}" class="pen comm-control comm-edit">Edit</a>
            {# Comm Delete URL #}
            <a href="{{ comm.get_delete_url }}?account={{ account.id }}" class="cancel comm-control">x</a>
        </span>
    </h6>
    <p class="co-item-date"on {{ comm.date }}></p>
    <p>{{ comm.date }}</p>
</li>