accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import AccountList, account_detail, account_cru


urlpatterns = [
    url(r'l/$', AccountList.as_view(), name='account_list'),
    url(r'p/(?P<uuid>[\w-]+)/$', account_detail, name='account_detail'),
    url(r'new/$', account_cru, name='account_new'),
    url(r'edit/(?P<uuid>[\w-]+)/$', account_cru, name='account_update'),
]

cheapcrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from marketing.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'login/$',auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'login/$', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    # url(r'logout/$', auth_views.logout, {'next_page':'/'}),
    url(r'logout/$', auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    url(r'^subscribe/', include('subscribers.urls',namespace='subscribers')),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
    url(r'^contact/', include('contacts.urls',namespace='contact')),
    url(r'^comm/', include('communications.urls',namespace='comm')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^$', HomePage.as_view(), name='home')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscribers/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import subscriber_new


urlpatterns = [
    url(r'signup/$', subscriber_new, name='sub_new')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}trackIt{% endblock %}</title>

    <!-- stylesheets -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    {% block extra-css %}{% endblock %}

    <script>
        $(function () {
            if (!window.utils.isMobile()) {
            // parallax header
            $(window).scroll(function() {
                var scroll = $(window).scrollTop(), 
                slowScroll = scroll/4,
                slowBg = slowScroll;

                $('.index-app-hero').css("background-position", "center " + -slowBg + "px");
            });
            }
        });
    </script>
</head>
<body>
    {% include 'navbar.html' %}

    <div style="min-height:800px;">{% block content %}{% endblock %}</div>

    {% include 'footer.html' %}
    <!-- javascript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'js/theme.min.js' %}"></script>
    <script src="{% static 'js/style.js' %}"></script>
    {% block extra-js %}{% endblock %}
</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="row">
        <div class="col-md-4">
            <div class="title">
            About tracIt
            </div>
            <ul class="menu">
            <li>
                <a href="#">Home Pages</a>
            </li>
            <li>
                <a href="#">Theme Features</a>
            </li>
            <li>
                <a href="#">Services</a>
            </li>
            <li>
                <a href="#">StoreFront</a>
            </li>
            <li>
                <a href="#">Portfolio</a>
            </li>
            </ul>
        </div>
        <div class="col-md-4">
            <div class="title">
            Connect with us
            </div>
            <ul class="menu">
            <li>
                <a href="#">
                <i class="fa fa-instagram"></i>
                Instagram
                </a>
            </li>
            <li>
                <a href="#">
                <i class="fa fa-twitter"></i>
                Twitter
                </a>
            </li>
            <li>
                <a href="#">
                <i class="fa fa-dribbble"></i>
                Dribbble
                </a>
            </li>
            <li>
                <a href="#">
                <i class="fa fa-facebook"></i>
                Facebook
                </a>
            </li>
            </ul>
        </div>
        <div class="col-md-4 newsletter">
            <div class="title">
                Get awesome updates
            </div>
            <p>
                Enter your email address for news and product launches in the Awesome Space.
            </p>

            <form class="newsletter-form" autocomplete="off">
            <input type="email" id="mc-email" class="form-control" placeholder="Email address" required />

            <button type="submit">
                <i class="fa fa-chevron-right"></i>
            </button>
            <label for="mc-email" class="text-white newsletter-feedback mt-3"></label>
            </form>
        </div>
        </div>
        <div class="bottom">
        <ul>
            <li><a href="#">Privacy</a></li>
            <li><a href="#">Legal</a></li>
            <li><a href="#">Language</a></li>
        </ul>
        </div>
    </div>
</footer>

templates/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}Login|{{ block.super }}{% endblock %}

{% block content %}


<div class="wrapper signin-page">
    <div class="container p-none" id="content-container">
        <div class="header text-center">
            <a href="" class="logo">
            <img src="images/logo-alt-b.png" />
            </a>
        </div>
        <!-- <form id="login-form" method="POST" action="{# url 'login' #}">
            {# csrf_token #}
            <div class="form-field">
                <input type="text" placeholder="Username" id="id_username" name="username" class="form-control">
            </div>
            <div class="form-field">
                <input type="password" placeholder="Password" id="id_password" name="password" class="form-control">
            </div>

            {# if form.errors #}
                <p class="label label-danger">
                    Your username and password didn't match.
                    Please try again.
                </p>
            {# endif #}
            <div class="form-action">
                <input type="submit" class="btn-shadow btn-shadow-primary" value="Login">
                <input type="hidden" name="next" value="{{ next }}">
            </div> -->
            <!-- <div class="container"> -->
            <h1 class="text-center">Login</h1>
                <form method="POST" id="login-form">
                    {% csrf_token %}
                    {% bootstrap_form form %}

                    <input type="submit" class="btn-shadow btn-shadow-primary btn-block" value="Login">
                    <input type="hidden" name="next" value="{{ next }}">
                    <!-- <input type="submit" class="btn btn-success" value="Login">
                </form> -->
                
                <!-- </div> -->
            <div class="form-bottom">
                <a href="">Forgot your password?</a>
            </div>
            <div class="form-bottom">
                Don't have an account yet?
                <a href="{% url 'subscribers:sub_new' %}">Sign up</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}


{% block content %}
<div class="container" style="padding-top:150px;">
    
    <form action="{% url 'home' %}" method="POST">
        {% csrf_token %}
        <h3>Are you sure you want to logout?</h3> 
        <input type="submit" class="btn-shadow btn-shadow-danger" value="Logout">
        <input type="hidden" name="next" value="{{ next }}">
    </form>
</div>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-transparent" role="navigation">
    <div class="container no-override">
        <a class="navbar-brand" href="/">
        <img src="img/logo-alt-w.png" class="d-none d-lg-inline mr-2 w-25" />
        trackIt
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbar-collapse">
        <ul class="navbar-nav">
            <li class="nav-item active dropdown">
            <!-- <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                Home pages
                <i class="ion-chevron-down"></i>
            </a>
            <div class="dropdown-menu" role="menu">
                <a class="dropdown-item" href="index.html">Business</a>
                <a class="dropdown-item" href="index-app.html">Web app</a>
            </div> -->
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    Account
                    <i class="ion-chevron-down"></i>
                </a>
                <div class="dropdown-menu" role="menu">
                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'accounts:account_list' %}">Accounts</a>
                    <a class="dropdown-item" href="/logout/">Logout</a>
                {% else %}
                    <a class="dropdown-item" href="/login/">Login</a>
                    <a class="dropdown-item" href="{% url 'subscribers:sub_new' %}">Register</a>
                {% endif %}
                </div>
            </li>
        </ul>
        </div>
    </div>
</nav>

templates/object_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{ object_name }} Confirm delete? |{{ block.super }}{% endblock %}

{% block content %}
<div id="content-container" class="container p-none" style="padding-top: 100px;">
    <div class="side-p">
        <h3>Are you sure?</h3>
        <p>You're about to delete {{ object }}. Please confirm.</p>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="button" class="btn btn-link" type="button" value="Cancel" onclick="window.history.go(-1);">
            <input type="submit" class="btn-shadow btn-shadow-danger" value="Confirm">
        </form>
    </div>
</div>
{% endblock %}